#[derive(Debug)]
#[allow(non_camel_case_types)]
#[derive(PartialEq)]
#[repr(u8)]
pub enum bytecode {
    opcode_nop = 0x00, // 0
         opcode_aconst_null, // 1
         opcode_sconst_m1, // 2
         opcode_sconst_0, // 3
         opcode_sconst_1, // 4
         opcode_sconst_2, // 5
         opcode_sconst_3, // 6
         opcode_sconst_4, // 7
         opcode_sconst_5, // 8
         opcode_iconst_m1, // 9
         opcode_iconst_0, // 10 - 0x0A
         opcode_iconst_1, // 11
         opcode_iconst_2, // 12
         opcode_iconst_3, // 13
         opcode_iconst_4, // 14
         opcode_iconst_5, // 15
         opcode_bspush, // 16
         opcode_sspush, // 17
         opcode_bipush, // 18
         opcode_sipush, // 19
         opcode_iipush, // 20
         opcode_aload, // 21
         opcode_sload, // 22
         opcode_iload, // 23
         opcode_aload_0, // 24
         opcode_aload_1, // 25
         opcode_aload_2, // 26
         opcode_aload_3, // 27
         opcode_sload_0, // 28
         opcode_sload_1, // 29
         opcode_sload_2, // 30
         opcode_sload_3, // 31
         opcode_iload_0, // 32
         opcode_iload_1, // 33
         opcode_iload_2, // 34
         opcode_iload_3, // 35
         opcode_aaload, // 36
         opcode_baload, // 37
         opcode_saload, // 38
         opcode_iaload, // 39
         opcode_astore, // 40
         opcode_sstore, // 41
         opcode_istore, // 42
         opcode_astore_0, // 43
         opcode_astore_1, // 44
         opcode_astore_2, // 45
         opcode_astore_3, // 46
         opcode_sstore_0, // 47
         opcode_sstore_1, // 48
         opcode_sstore_2, // 49
         opcode_sstore_3, // 50
         opcode_istore_0, // 51
         opcode_istore_1, // 52
         opcode_istore_2, // 53
         opcode_istore_3, // 54
         opcode_aastore, // 55
         opcode_bastore, // 56
         opcode_sastore, // 57
         opcode_iastore, // 58
         opcode_pop, // 59
         opcode_pop2, // 60
         opcode_dup, // 61
         opcode_dup2, // 62
         opcode_dup_x, // 63
         opcode_swap_x, // 64
         opcode_sadd, // 65
         opcode_iadd, // 66
         opcode_ssub, // 67
         opcode_isub, // 68
         opcode_smul, // 69
         opcode_imul, // 70
         opcode_sdiv, // 71
         opcode_idiv, // 72
         opcode_srem, // 73
         opcode_irem, // 74
         opcode_sneg, // 75
         opcode_ineg, // 76
         opcode_sshl, // 77
         opcode_ishl, // 78
         opcode_sshr, // 79
         opcode_ishr, // 80
         opcode_sushr, // 81
         opcode_iushr, // 82
         opcode_sand, // 83
         opcode_iand, // 84
         opcode_sor, // 85
         opcode_ior, // 86
         opcode_sxor, // 87
         opcode_ixor, // 88
         opcode_sinc, // 89
         opcode_iinc, // 90
         opcode_s2b, // 91
         opcode_s2i, // 92
         opcode_i2b, // 93
         opcode_i2s, // 94
         opcode_icmp, // 95
         opcode_ifeq, // 96
         opcode_ifne, // 97
         opcode_iflt, // 98
         opcode_ifge, // 99
         opcode_ifgt, // 100
         opcode_ifle, // 101
         opcode_ifnull, // 102
         opcode_ifnonnull, // 103
         opcode_if_acmpeq, // 104
         opcode_if_acmpne, // 105
         opcode_if_scmpeq, // 106
         opcode_if_scmpne, // 107
         opcode_if_scmplt, // 108
         opcode_if_scmpge, // 109
         opcode_if_scmpgt, // 110
         opcode_if_scmple, // 111
         opcode_goto, // 112
         opcode_jsr, // 113
         opcode_ret, // 114
         opcode_stableswitch, // 115
         opcode_itableswitch, // 116
         opcode_slookupswitch, // 117
         opcode_ilookupswitch, // 118
         opcode_areturn, // 119
         opcode_sreturn, // 120
         opcode_ireturn, // 121
         opcode_return, // 122
         opcode_getstatic_a, // 123
         opcode_getstatic_b, // 124
         opcode_getstatic_s, // 125
         opcode_getstatic_i, // 126
         opcode_putstatic_a, // 127
         opcode_putstatic_b, // 128
         opcode_putstatic_s, // 129
         opcode_putstatic_i, // 130
         opcode_getfield_a, // 131
         opcode_getfield_b, // 132
         opcode_getfield_s, // 133
         opcode_getfield_i, // 134
         opcode_putfield_a, // 135
         opcode_putfield_b, // 136
         opcode_putfield_s, // 137
         opcode_putfield_i, // 138
         opcode_invokevirtual, // 139
         opcode_invokespecial, // 140
         opcode_invokestatic, // 141
         opcode_invokeinterface, // 142
         opcode_new, // 143
         opcode_newarray, // 144
         opcode_anewarray, // 145
         opcode_arraylength, // 146
         opcode_athrow, // 147
         opcode_checkcast, // 148
         opcode_instanceof, // 149
         opcode_sinc_w, // 150
         opcode_iinc_w, // 151
         opcode_ifeq_w, // 152
         opcode_ifne_w, // 153
         opcode_iflt_w, // 154
         opcode_ifge_w, // 155
         opcode_ifgt_w, // 156
         opcode_ifle_w, // 157
         opcode_ifnull_w, // 158
         opcode_ifnonnull_w, // 159
         opcode_if_acmpeq_w, // 160
         opcode_if_acmpne_w, // 161
         opcode_if_scmpeq_w, // 162
         opcode_if_scmpne_w, // 163
         opcode_if_scmplt_w, // 164
         opcode_if_scmpge_w, // 165
         opcode_if_scmpgt_w, // 166
         opcode_if_scmple_w, // 167
         opcode_goto_w, // 168
         opcode_getfield_a_w, // 169
         opcode_getfield_b_w, // 170
         opcode_getfield_s_w, // 171
         opcode_getfield_i_w, // 172
         opcode_getfield_a_this, // 173
         opcode_getfield_b_this, // 174
         opcode_getfield_s_this, // 175
         opcode_getfield_i_this, // 176
         opcode_putfield_a_w, // 177
         opcode_putfield_b_w, // 178
         opcode_putfield_s_w, // 179
         opcode_putfield_i_w, // 180
         opcode_putfield_a_this, // 181
         opcode_putfield_b_this, // 182
         opcode_putfield_s_this, // 183
         opcode_putfield_i_this, // 184
         opcode_END,// indicator for the end of standard opcodes
         opcode_impdep1, // 254
         opcode_impdep2  // 255
}
