use jcvmerrors::InterpreterError;

#[allow(non_camel_case_types)]
#[derive(Debug,PartialEq)]
#[repr(u8)]
pub enum bytecode {
    opcode_nop = 0x00, // 0
    opcode_aconst_null, // 1
    opcode_sconst_m1, // 2
    opcode_sconst_0, // 3
    opcode_sconst_1, // 4
    opcode_sconst_2, // 5
    opcode_sconst_3, // 6
    opcode_sconst_4, // 7
    opcode_sconst_5, // 8
    opcode_iconst_m1, // 9
    opcode_iconst_0, // 10 - 0x0A
    opcode_iconst_1, // 11
    opcode_iconst_2, // 12
    opcode_iconst_3, // 13
    opcode_iconst_4, // 14
    opcode_iconst_5, // 15
    opcode_bspush, // 16
    opcode_sspush, // 17
    opcode_bipush, // 18
    opcode_sipush, // 19
    opcode_iipush, // 20
    opcode_aload, // 21
    opcode_sload, // 22
    opcode_iload, // 23
    opcode_aload_0, // 24
    opcode_aload_1, // 25
    opcode_aload_2, // 26
    opcode_aload_3, // 27
    opcode_sload_0, // 28
    opcode_sload_1, // 29
    opcode_sload_2, // 30
    opcode_sload_3, // 31
    opcode_iload_0, // 32
    opcode_iload_1, // 33
    opcode_iload_2, // 34
    opcode_iload_3, // 35
    opcode_aaload, // 36
    opcode_baload, // 37
    opcode_saload, // 38
    opcode_iaload, // 39
    opcode_astore, // 40
    opcode_sstore, // 41
    opcode_istore, // 42
    opcode_astore_0, // 43
    opcode_astore_1, // 44
    opcode_astore_2, // 45
    opcode_astore_3, // 46
    opcode_sstore_0, // 47
    opcode_sstore_1, // 48
    opcode_sstore_2, // 49
    opcode_sstore_3, // 50
    opcode_istore_0, // 51
    opcode_istore_1, // 52
    opcode_istore_2, // 53
    opcode_istore_3, // 54
    opcode_aastore, // 55
    opcode_bastore, // 56
    opcode_sastore, // 57
    opcode_iastore, // 58
    opcode_pop, // 59
    opcode_pop2, // 60
    opcode_dup, // 61
    opcode_dup2, // 62
    opcode_dup_x, // 63
    opcode_swap_x, // 64
    opcode_sadd, // 65
    opcode_iadd, // 66
    opcode_ssub, // 67
    opcode_isub, // 68
    opcode_smul, // 69
    opcode_imul, // 70
    opcode_sdiv, // 71
    opcode_idiv, // 72
    opcode_srem, // 73
    opcode_irem, // 74
    opcode_sneg, // 75
    opcode_ineg, // 76
    opcode_sshl, // 77
    opcode_ishl, // 78
    opcode_sshr, // 79
    opcode_ishr, // 80
    opcode_sushr, // 81
    opcode_iushr, // 82
    opcode_sand, // 83
    opcode_iand, // 84
    opcode_sor, // 85
    opcode_ior, // 86
    opcode_sxor, // 87
    opcode_ixor, // 88
    opcode_sinc, // 89
    opcode_iinc, // 90
    opcode_s2b, // 91
    opcode_s2i, // 92
    opcode_i2b, // 93
    opcode_i2s, // 94
    opcode_icmp, // 95
    opcode_ifeq, // 96
    opcode_ifne, // 97
    opcode_iflt, // 98
    opcode_ifge, // 99
    opcode_ifgt, // 100
    opcode_ifle, // 101
    opcode_ifnull, // 102
    opcode_ifnonnull, // 103
    opcode_if_acmpeq, // 104
    opcode_if_acmpne, // 105
    opcode_if_scmpeq, // 106
    opcode_if_scmpne, // 107
    opcode_if_scmplt, // 108
    opcode_if_scmpge, // 109
    opcode_if_scmpgt, // 110
    opcode_if_scmple, // 111
    opcode_goto, // 112
    opcode_jsr, // 113
    opcode_ret, // 114
    opcode_stableswitch, // 115
    opcode_itableswitch, // 116
    opcode_slookupswitch, // 117
    opcode_ilookupswitch, // 118
    opcode_areturn, // 119
    opcode_sreturn, // 120
    opcode_ireturn, // 121
    opcode_return, // 122
    opcode_getstatic_a, // 123
    opcode_getstatic_b, // 124
    opcode_getstatic_s, // 125
    opcode_getstatic_i, // 126
    opcode_putstatic_a, // 127
    opcode_putstatic_b, // 128
    opcode_putstatic_s, // 129
    opcode_putstatic_i, // 130
    opcode_getfield_a, // 131
    opcode_getfield_b, // 132
    opcode_getfield_s, // 133
    opcode_getfield_i, // 134
    opcode_putfield_a, // 135
    opcode_putfield_b, // 136
    opcode_putfield_s, // 137
    opcode_putfield_i, // 138
    opcode_invokevirtual, // 139
    opcode_invokespecial, // 140
    opcode_invokestatic, // 141
    opcode_invokeinterface, // 142
    opcode_new, // 143
    opcode_newarray, // 144
    opcode_anewarray, // 145
    opcode_arraylength, // 146
    opcode_athrow, // 147
    opcode_checkcast, // 148
    opcode_instanceof, // 149
    opcode_sinc_w, // 150
    opcode_iinc_w, // 151
    opcode_ifeq_w, // 152
    opcode_ifne_w, // 153
    opcode_iflt_w, // 154
    opcode_ifge_w, // 155
    opcode_ifgt_w, // 156
    opcode_ifle_w, // 157
    opcode_ifnull_w, // 158
    opcode_ifnonnull_w, // 159
    opcode_if_acmpeq_w, // 160
    opcode_if_acmpne_w, // 161
    opcode_if_scmpeq_w, // 162
    opcode_if_scmpne_w, // 163
    opcode_if_scmplt_w, // 164
    opcode_if_scmpge_w, // 165
    opcode_if_scmpgt_w, // 166
    opcode_if_scmple_w, // 167
    opcode_goto_w, // 168
    opcode_getfield_a_w, // 169
    opcode_getfield_b_w, // 170
    opcode_getfield_s_w, // 171
    opcode_getfield_i_w, // 172
    opcode_getfield_a_this, // 173
    opcode_getfield_b_this, // 174
    opcode_getfield_s_this, // 175
    opcode_getfield_i_this, // 176
    opcode_putfield_a_w, // 177
    opcode_putfield_b_w, // 178
    opcode_putfield_s_w, // 179
    opcode_putfield_i_w, // 180
    opcode_putfield_a_this, // 181
    opcode_putfield_b_this, // 182
    opcode_putfield_s_this, // 183
    opcode_putfield_i_this, // 184
    opcode_END, // indicator for the end of standard opcodes
    opcode_impdep1, // 254
    opcode_impdep2, // 255
}

impl bytecode {
    pub fn from(b: u8) -> Result<bytecode,InterpreterError> {
        match b {
            0 => Ok(bytecode::opcode_nop),
            1 => Ok(bytecode::opcode_aconst_null),
            2 => Ok(bytecode::opcode_sconst_m1),
            3 => Ok(bytecode::opcode_sconst_0),
            4 => Ok(bytecode::opcode_sconst_1),
            5 => Ok(bytecode::opcode_sconst_2),
            6 => Ok(bytecode::opcode_sconst_3),
            7 => Ok(bytecode::opcode_sconst_4),
            8 => Ok(bytecode::opcode_sconst_5),
            9 => Ok(bytecode::opcode_iconst_m1),
            10 => Ok(bytecode::opcode_iconst_0),
            11 => Ok(bytecode::opcode_iconst_1),
            12 => Ok(bytecode::opcode_iconst_2),
            13 => Ok(bytecode::opcode_iconst_3),
            14 => Ok(bytecode::opcode_iconst_4),
            15 => Ok(bytecode::opcode_iconst_5),
            16 => Ok(bytecode::opcode_bspush),
            17 => Ok(bytecode::opcode_sspush),
            18 => Ok(bytecode::opcode_bipush),
            19 => Ok(bytecode::opcode_sipush),
            20 => Ok(bytecode::opcode_iipush),
            21 => Ok(bytecode::opcode_aload),
            22 => Ok(bytecode::opcode_sload),
            23 => Ok(bytecode::opcode_iload),
            24 => Ok(bytecode::opcode_aload_0),
            25 => Ok(bytecode::opcode_aload_1),
            26 => Ok(bytecode::opcode_aload_2),
            27 => Ok(bytecode::opcode_aload_3),
            28 => Ok(bytecode::opcode_sload_0),
            29 => Ok(bytecode::opcode_sload_1),
            30 => Ok(bytecode::opcode_sload_2),
            31 => Ok(bytecode::opcode_sload_3),
            32 => Ok(bytecode::opcode_iload_0),
            33 => Ok(bytecode::opcode_iload_1),
            34 => Ok(bytecode::opcode_iload_2),
            35 => Ok(bytecode::opcode_iload_3),
            36 => Ok(bytecode::opcode_aaload),
            37 => Ok(bytecode::opcode_baload),
            38 => Ok(bytecode::opcode_saload),
            39 => Ok(bytecode::opcode_iaload),
            40 => Ok(bytecode::opcode_astore),
            41 => Ok(bytecode::opcode_sstore),
            42 => Ok(bytecode::opcode_istore),
            43 => Ok(bytecode::opcode_astore_0),
            44 => Ok(bytecode::opcode_astore_1),
            45 => Ok(bytecode::opcode_astore_2),
            46 => Ok(bytecode::opcode_astore_3),
            47 => Ok(bytecode::opcode_sstore_0),
            48 => Ok(bytecode::opcode_sstore_1),
            49 => Ok(bytecode::opcode_sstore_2),
            50 => Ok(bytecode::opcode_sstore_3),
            51 => Ok(bytecode::opcode_istore_0),
            52 => Ok(bytecode::opcode_istore_1),
            53 => Ok(bytecode::opcode_istore_2),
            54 => Ok(bytecode::opcode_istore_3),
            55 => Ok(bytecode::opcode_aastore),
            56 => Ok(bytecode::opcode_bastore),
            57 => Ok(bytecode::opcode_sastore),
            58 => Ok(bytecode::opcode_iastore),
            59 => Ok(bytecode::opcode_pop),
            60 => Ok(bytecode::opcode_pop2),
            61 => Ok(bytecode::opcode_dup),
            62 => Ok(bytecode::opcode_dup2),
            63 => Ok(bytecode::opcode_dup_x),
            64 => Ok(bytecode::opcode_swap_x),
            65 => Ok(bytecode::opcode_sadd),
            66 => Ok(bytecode::opcode_iadd),
            67 => Ok(bytecode::opcode_ssub),
            68 => Ok(bytecode::opcode_isub),
            69 => Ok(bytecode::opcode_smul),
            70 => Ok(bytecode::opcode_imul),
            71 => Ok(bytecode::opcode_sdiv),
            72 => Ok(bytecode::opcode_idiv),
            73 => Ok(bytecode::opcode_srem),
            74 => Ok(bytecode::opcode_irem),
            75 => Ok(bytecode::opcode_sneg),
            76 => Ok(bytecode::opcode_ineg),
            77 => Ok(bytecode::opcode_sshl),
            78 => Ok(bytecode::opcode_ishl),
            79 => Ok(bytecode::opcode_sshr),
            80 => Ok(bytecode::opcode_ishr),
            81 => Ok(bytecode::opcode_sushr),
            82 => Ok(bytecode::opcode_iushr),
            83 => Ok(bytecode::opcode_sand),
            84 => Ok(bytecode::opcode_iand),
            85 => Ok(bytecode::opcode_sor),
            86 => Ok(bytecode::opcode_ior),
            87 => Ok(bytecode::opcode_sxor),
            88 => Ok(bytecode::opcode_ixor),
            89 => Ok(bytecode::opcode_sinc),
            90 => Ok(bytecode::opcode_iinc),
            91 => Ok(bytecode::opcode_s2b),
            92 => Ok(bytecode::opcode_s2i),
            93 => Ok(bytecode::opcode_i2b),
            94 => Ok(bytecode::opcode_i2s),
            95 => Ok(bytecode::opcode_icmp),
            96 => Ok(bytecode::opcode_ifeq),
            97 => Ok(bytecode::opcode_ifne),
            98 => Ok(bytecode::opcode_iflt),
            99 => Ok(bytecode::opcode_ifge),
            100 => Ok(bytecode::opcode_ifgt),
            101 => Ok(bytecode::opcode_ifle),
            102 => Ok(bytecode::opcode_ifnull),
            103 => Ok(bytecode::opcode_ifnonnull),
            104 => Ok(bytecode::opcode_if_acmpeq),
            105 => Ok(bytecode::opcode_if_acmpne),
            106 => Ok(bytecode::opcode_if_scmpeq),
            107 => Ok(bytecode::opcode_if_scmpne),
            108 => Ok(bytecode::opcode_if_scmplt),
            109 => Ok(bytecode::opcode_if_scmpge),
            110 => Ok(bytecode::opcode_if_scmpgt),
            111 => Ok(bytecode::opcode_if_scmple),
            112 => Ok(bytecode::opcode_goto),
            113 => Ok(bytecode::opcode_jsr),
            114 => Ok(bytecode::opcode_ret),
            115 => Ok(bytecode::opcode_stableswitch),
            116 => Ok(bytecode::opcode_itableswitch),
            117 => Ok(bytecode::opcode_slookupswitch),
            118 => Ok(bytecode::opcode_ilookupswitch),
            119 => Ok(bytecode::opcode_areturn),
            120 => Ok(bytecode::opcode_sreturn),
            121 => Ok(bytecode::opcode_ireturn),
            122 => Ok(bytecode::opcode_return),
            123 => Ok(bytecode::opcode_getstatic_a),
            124 => Ok(bytecode::opcode_getstatic_b),
            125 => Ok(bytecode::opcode_getstatic_s),
            126 => Ok(bytecode::opcode_getstatic_i),
            127 => Ok(bytecode::opcode_putstatic_a),
            128 => Ok(bytecode::opcode_putstatic_b),
            129 => Ok(bytecode::opcode_putstatic_s),
            130 => Ok(bytecode::opcode_putstatic_i),
            131 => Ok(bytecode::opcode_getfield_a),
            132 => Ok(bytecode::opcode_getfield_b),
            133 => Ok(bytecode::opcode_getfield_s),
            134 => Ok(bytecode::opcode_getfield_i),
            135 => Ok(bytecode::opcode_putfield_a),
            136 => Ok(bytecode::opcode_putfield_b),
            137 => Ok(bytecode::opcode_putfield_s),
            138 => Ok(bytecode::opcode_putfield_i),
            139 => Ok(bytecode::opcode_invokevirtual),
            140 => Ok(bytecode::opcode_invokespecial),
            141 => Ok(bytecode::opcode_invokestatic),
            142 => Ok(bytecode::opcode_invokeinterface),
            143 => Ok(bytecode::opcode_new),
            144 => Ok(bytecode::opcode_newarray),
            145 => Ok(bytecode::opcode_anewarray),
            146 => Ok(bytecode::opcode_arraylength),
            147 => Ok(bytecode::opcode_athrow),
            148 => Ok(bytecode::opcode_checkcast),
            149 => Ok(bytecode::opcode_instanceof),
            150 => Ok(bytecode::opcode_sinc_w),
            151 => Ok(bytecode::opcode_iinc_w),
            152 => Ok(bytecode::opcode_ifeq_w),
            153 => Ok(bytecode::opcode_ifne_w),
            154 => Ok(bytecode::opcode_iflt_w),
            155 => Ok(bytecode::opcode_ifge_w),
            156 => Ok(bytecode::opcode_ifgt_w),
            157 => Ok(bytecode::opcode_ifle_w),
            158 => Ok(bytecode::opcode_ifnull_w),
            159 => Ok(bytecode::opcode_ifnonnull_w),
            160 => Ok(bytecode::opcode_if_acmpeq_w),
            161 => Ok(bytecode::opcode_if_acmpne_w),
            162 => Ok(bytecode::opcode_if_scmpeq_w),
            163 => Ok(bytecode::opcode_if_scmpne_w),
            164 => Ok(bytecode::opcode_if_scmplt_w),
            165 => Ok(bytecode::opcode_if_scmpge_w),
            166 => Ok(bytecode::opcode_if_scmpgt_w),
            167 => Ok(bytecode::opcode_if_scmple_w),
            168 => Ok(bytecode::opcode_goto_w),
            169 => Ok(bytecode::opcode_getfield_a_w),
            170 => Ok(bytecode::opcode_getfield_b_w),
            171 => Ok(bytecode::opcode_getfield_s_w),
            172 => Ok(bytecode::opcode_getfield_i_w),
            173 => Ok(bytecode::opcode_getfield_a_this),
            174 => Ok(bytecode::opcode_getfield_b_this),
            175 => Ok(bytecode::opcode_getfield_s_this),
            176 => Ok(bytecode::opcode_getfield_i_this),
            177 => Ok(bytecode::opcode_putfield_a_w),
            178 => Ok(bytecode::opcode_putfield_b_w),
            179 => Ok(bytecode::opcode_putfield_s_w),
            180 => Ok(bytecode::opcode_putfield_i_w),
            181 => Ok(bytecode::opcode_putfield_a_this),
            182 => Ok(bytecode::opcode_putfield_b_this),
            183 => Ok(bytecode::opcode_putfield_s_this),
            184 => Ok(bytecode::opcode_putfield_i_this),
            185 => Ok(bytecode::opcode_END),
            186 => Ok(bytecode::opcode_impdep1),
        // 186 => bytecode::opcode_impdep1, // 254
            // 187 => bytecode::opcode_impdep2,       
            _ => Err(InterpreterError::UnrecognizedBytecode)
        }
    }
}